(lang dune 3.16)

(using coq 0.9)

(package
  ( allow_empty)
  (name rac_formal)
  (depends
    (coq-core (and (< 8.21) (>= 8.20)))
    coq-record-update
    coq-mmaps
    coq-equations
  )
)

(generate_opam_files true)
